### ISSUE TITLE
feature: Improve the styling of the Navbar component and change the color

### ISSUE THREAD

**Issue by hsayvaidya23** [hsayvaidya23/NewsApp#20]
**Issue**: The current styling of the Navbar component is basic and could be improved. The color of the Navbar is also not very visually appealing.

**Feature** **request**: I would like to request that the styling of the Navbar component be improved and that the color of the Navbar be changed to something more visually appealing.

**Specific** **suggestions**:

- Add hover and selection states to the Navbar links.
- Change the font and font size of the Navbar links.
- Add a border to the Navbar.
- Change the background color of the Navbar to a more visually appealing color.

**Additional notes**:

Please make sure that the improved styling of the Navbar component is consistent with the rest of the application's styling.
Please test the improved styling of the Navbar component in all major browsers and devices.

**Comment by bharath090909** [comment]
@hsayvaidya23 i can work on this, can you assign this to me ?

**Comment by hsayvaidya23** [comment]
Yes, please go ahead

**Comment by hsayvaidya23** [comment]
@bharath090909 please add 
fixes #20  in your PR 
and create a new PR Request

**Comment by bharath090909** [comment]
Yes i will complete it by the EOD.

**Comment by bharath090909** [comment]
I have raised a PR Please check it and  let me know if any changes required.
